const notificationTypes = {
  OPEN_BOOKING_NOTIFICATION: "OPEN_BOOKING_NOTIFICATION",
  CONFIRM_BOOKING_SUCCESS: "CONFIRM_BOOKING_SUCCESS",
  CONFIRM_BOOKING_FAIL: "CONFIRM_BOOKING_FAIL",
  CHECK_IN_SUCCESS: "CHECK_IN_SUCCESS",
  CHECK_OUT_SUCCESS: "CHECK_OUT_SUCCESS",
};

export default notificationTypes;
