const notificationTypes = {
  OPEN_BOOKING_NOTIFICATION: "OPEN_BOOKING_NOTIFICATION",
  CONFIRM_BOOKING_SUCCESS: "CONFIRM_BOOKING_SUCCESS",
  CONFIRM_BOOKING_FAIL: "CONFIRM_BOOKING_FAIL",
};

export default notificationTypes;
